# Generated by Django 3.0.4 on 2020-06-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
